# =======================================================
# netlify.toml — Configurações de Build para Next.js (Netlify)
# =======================================================

[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
